service: nutrition-bot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  post:
    handler: handler.hello
    events:
      - http:
          path: sendMessage
          method: post
          cors: true